import Head from "next/head";
import { Inter } from "next/font/google";
import {
  News,
  About,
  Mission,
  History,
  Admission,
  GraduateProgram,
  Department,
  NavigationBar,
  Footer,
  SportsActivities,
  Apply,
  Tution,
  Scholarship,
  TabSlide,
} from "../components/home/Index";
import CampusInfo from "@/components/home/CampusInfo";
import Sponsors from "@/components/home/Sponser";
import { getValueByKey } from "@/apis";
import HeaderFooter from "@/components/global/HeaderFooter";
import Events from "@/components/home/Events";
const inter = Inter({ subsets: ["latin"] });

export default function Home({
  admissionParas,
  historyData,
  sportsData,
  overview,
}) {
  return (
    <>
      <Head>
        <title>SIBAU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ overflowX: "hidden" }}>
        <>
          <HeaderFooter>
            <TabSlide />
            <About />
            <Mission data={overview} />
            <History data={historyData} />
            <CampusInfo />
            <GraduateProgram />

            <Department />
            <Admission />
            <Apply />
            <Scholarship />
            <Tution />
            <SportsActivities />
            <News />
            {/* <Events /> */}

            <Sponsors />
          </HeaderFooter>{" "}
        </>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let sportsData = {};
  let historyData = {};
  let admissionParas = {};
  let overview = {};

  try {
    const [sportsResult, historyResult, admissionParasResult, overviewResult] =
      await Promise.all([
        getValueByKey("home-sport-activity"),
        getValueByKey("home-history-data"),
        getValueByKey("admission-overview-paras"),
        getValueByKey("home-overview"),
      ]);

    overview = JSON.parse(overviewResult.value);
    admissionParas = JSON.parse(admissionParasResult.value);
    sportsData = JSON.parse(sportsResult.value);
    historyData = JSON.parse(historyResult.value);
  } catch (error) {
    console.error("Error fetching data:", error);
  }
  return {
    props: {
      admissionParas,
      historyData,
      sportsData,
      overview,
    },
  };
}
