export const ABOUT_STATISTIC = 'ABOUT_STATISTIC';
export const GALLERY = 'GALLERY';
export const ABOUT_BANNER = 'ABOUT_BANNER';
export const HISTORY_DETAILS = 'HISTORY_DETAILS';
export const TESTIMONIALS = 'TESTIMONIALS';
export const FOOTER_CONTACT_INFO = 'FOOTER_CONTACT_INFO';
export const ACADEMICS_OVERVIEW = "ACADEMICS_OVERVIEW";
export const HOME_STATISTIC = "HOME_STATISTIC";
export const ABOUT_HISTORY = "ABOUT_HISTORY";
export const ABOUT_MISSION = "ABOUT_MISSION";
export const ABOUT_VIDEO = "ABOUT_VIDEO";

export const SERVER = 'http://localhost:5001';

export default {
    ABOUT_STATISTIC,
    GALLERY,
    ABOUT_BANNER,
    HISTORY_DETAILS,
    TESTIMONIALS,
    FOOTER_CONTACT_INFO,
    ACADEMICS_OVERVIEW,
    HOME_STATISTIC,
    ABOUT_HISTORY,
    ABOUT_MISSION,
    ABOUT_VIDEO,
    SERVER
};
