export const ABOUT_STATISTIC = 'ABOUT_STATISTIC';
export const GALLERY = 'GALLERY';
export const ABOUT_BANNER = 'ABOUT_BANNER';
export const HISTORY_DETAILS = 'HISTORY_DETAILS';
export const TESTIMONIALS = 'TESTIMONIALS';
export const FOOTER_CONTACT_INFO = 'FOOTER_CONTACT_INFO';
export const ACADEMICS_OVERVIEW = "ACADEMICS_OVERVIEW";
export default {
    ABOUT_STATISTIC,
    GALLERY,
    ABOUT_BANNER,
    HISTORY_DETAILS,
    TESTIMONIALS,
    FOOTER_CONTACT_INFO,
    ACADEMICS_OVERVIEW
};
